<?php
/**
 * Autoloader of the scoped third-party libraries of the theme.
 *
 * Generated by bin/build-scoped-libs.php. Do not edit; run composer vendor:scope.
 * The file has no side effects besides registering the autoloader, so CLI
 * tools may load it without WordPress.
 *
 * @package Creationell\WpTheme
 */

declare(strict_types=1);

spl_autoload_register(
	static function ( string $class_name ): void {
		static $prefixes = array(
			array( 'Creationell\\WpTheme\\Vendor\\Symfony\\Component\\Filesystem\\', array( 'symfony/filesystem' ) ),
			array( 'Creationell\\WpTheme\\Vendor\\Psr\\Http\\Message\\', array( 'psr/http-factory/src', 'psr/http-message/src' ) ),
			array( 'Creationell\\WpTheme\\Vendor\\ScssPhp\\ScssPhp\\', array( 'scssphp/scssphp/src' ) ),
			array( 'Creationell\\WpTheme\\Vendor\\Sabberworm\\CSS\\', array( 'sabberworm/php-css-parser/src' ) ),
			array( 'Creationell\\WpTheme\\Vendor\\League\\Uri\\', array( 'league/uri', 'league/uri-interfaces' ) ),
			array( 'Creationell\\WpTheme\\Vendor\\SourceSpan\\', array( 'scssphp/source-span/src' ) ),
			array( 'Creationell\\WpTheme\\Vendor\\MoodleHQ\\', array( 'moodlehq/rtlcss-php/src/MoodleHQ' ) ),
		);
		foreach ( $prefixes as $entry ) {
			if ( ! str_starts_with( $class_name, $entry[0] ) ) {
				continue;
			}
			$relative = str_replace( '\\', '/', substr( $class_name, strlen( $entry[0] ) ) ) . '.php';
			foreach ( $entry[1] as $dir ) {
				$file = __DIR__ . '/' . $dir . '/' . $relative;
				if ( is_file( $file ) ) {
					require_once $file;
					return;
				}
			}
		}
	}
);
require_once __DIR__ . '/sabberworm/php-css-parser/src/Rule/Rule.php';
require_once __DIR__ . '/sabberworm/php-css-parser/src/RuleSet/RuleContainer.php';
